"""multi-tenant: add user_id to strategies, trades, backtests

Revision ID: 11389f98a045
Revises: d47d256d06f5
Create Date: 2026-04-27 01:20:47.665489

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '11389f98a045'
down_revision: Union[str, None] = 'd47d256d06f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Text(), server_default='local-dev', nullable=False))
        batch_op.create_index(batch_op.f('ix_backtests_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'local-dev'"))

    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Text(), server_default='local-dev', nullable=False))
        batch_op.create_index(batch_op.f('ix_strategies_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Text(), server_default='local-dev', nullable=False))
        batch_op.create_index(batch_op.f('ix_trades_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'local-dev'"))

    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtests_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
