"""initial schema

Revision ID: d47d256d06f5
Revises: 
Create Date: 2026-04-26 21:33:24.903823

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd47d256d06f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('kucoin_key_enc', sa.Text(), nullable=True),
    sa.Column('kucoin_secret_enc', sa.Text(), nullable=True),
    sa.Column('kucoin_passphrase_enc', sa.Text(), nullable=True),
    sa.Column('openrouter_key_enc', sa.Text(), nullable=True),
    sa.Column('preferred_model', sa.Text(), nullable=True),
    sa.Column('max_position_pct', sa.Float(), nullable=True),
    sa.Column('max_open_trades', sa.Integer(), nullable=True),
    sa.Column('max_daily_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('default_stoploss_pct', sa.Float(), nullable=True),
    sa.Column('trailing_stop_pct', sa.Float(), nullable=True),
    sa.Column('take_profit_pct', sa.Float(), nullable=True),
    sa.Column('position_adjustment', sa.Boolean(), nullable=True),
    sa.Column('auto_trade_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_trade_mode', sa.Text(), nullable=True),
    sa.Column('auto_trade_min_score', sa.Float(), nullable=True),
    sa.Column('auto_trade_timeframe', sa.Text(), nullable=True),
    sa.Column('auto_trade_scan_interval_s', sa.Integer(), nullable=True),
    sa.Column('telegram_token', sa.Text(), nullable=True),
    sa.Column('telegram_chat_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_config_user_id_unique', ['user_id'], unique=True)

    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('generated_code', sa.Text(), nullable=False),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('indicators', sa.JSON(), nullable=True),
    sa.Column('timeframe', sa.Text(), nullable=True),
    sa.Column('pairs', sa.JSON(), nullable=True),
    sa.Column('stoploss', sa.Float(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('auto_trade_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_trade_mode', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('pair', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('actor_ip', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_audit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_audit_event'), ['event'], unique=False)
        batch_op.create_index('ix_trade_audit_user_event_time', ['user_id', 'event', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_audit_user_id'), ['user_id'], unique=False)

    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('timerange', sa.Text(), nullable=True),
    sa.Column('starting_balance', sa.Float(), nullable=True),
    sa.Column('total_profit', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('avg_duration', sa.Text(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('pair', sa.Text(), nullable=False),
    sa.Column('side', sa.Text(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('profit_pct', sa.Float(), nullable=True),
    sa.Column('profit_abs', sa.Float(), nullable=True),
    sa.Column('stoploss_price', sa.Float(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.CheckConstraint("mode IN ('paper', 'live')"),
    sa.CheckConstraint("side IN ('long', 'short')"),
    sa.CheckConstraint("status IN ('open', 'closed', 'cancelled')"),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('backtests')
    with op.batch_alter_table('trade_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_audit_user_id'))
        batch_op.drop_index('ix_trade_audit_user_event_time')
        batch_op.drop_index(batch_op.f('ix_trade_audit_event'))
        batch_op.drop_index(batch_op.f('ix_trade_audit_created_at'))

    op.drop_table('trade_audit')
    op.drop_table('strategies')
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_index('ix_config_user_id_unique')
        batch_op.drop_index(batch_op.f('ix_config_user_id'))

    op.drop_table('config')
    # ### end Alembic commands ###
